name: Create Release

on:
  workflow_call:
    inputs:
      SERIAL:
        description: "Zone serial number"
        type: string
        required: true

jobs:
  release:
    name: "Create release"
    runs-on: ubuntu-22.04
    steps:
      - name: "Check-out"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "v${{ inputs.SERIAL }}"

      - name: "Generate release changelog"
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true" # set to false if no tags exist (buggy with only one tag)
          stripHeaders: "true"
          stripGeneratorNotice: "true"

      - name: "Create GitHub release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ inputs.SERIAL }}"
          name: "Serial ${{ inputs.SERIAL }}"
          body: "${{ steps.generate-release-changelog.outputs.changelog }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: False
