name: Verify Bind9 Zones

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  named-checkzone:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Run named-checkzone
      uses: grramos/action-named-checkzone@v1.0.1
